name: Publish package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
    - name: Build
      run: dotnet build ./src/MMLib.MediatR.Generators.csproj --configuration Release
    - name: Test
      run: dotnet test ./tests/MMLib.MediatR.Generators.Tests/MMLib.MediatR.Generators.Tests.csproj
    - name: Generate nuget package
      run: dotnet pack  ./src/MMLib.MediatR.Generators.csproj --configuration Release -o nupkg
    - name: Publish nuget package
      run: dotnet nuget push "**/*.nupkg" -k $env:nuget_api_key --source "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./nupkg
