name: Pull Request

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
    - name: Build
      run: dotnet build ./MMLib.MediatR.Generators.sln --configuration Release
    - name: Test
      run: dotnet test ./MMLib.MediatR.Generators.sln --configuration Release
